<?php
// Database credentials
define("ALLOC_DB_NAME","CONFIG_VAR_ALLOC_DB_NAME");
define("ALLOC_DB_USER","CONFIG_VAR_ALLOC_DB_USER");
define("ALLOC_DB_PASS","CONFIG_VAR_ALLOC_DB_PASS");
define("ALLOC_DB_HOST","CONFIG_VAR_ALLOC_DB_HOST");
define("ATTACHMENTS_DIR","CONFIG_VAR_ALLOC_DOCS_DIR");
?>
