-- Part 2: Make structure easier to manage, more in line with postgres syntax

ALTER TABLE skill CHANGE skillID skillID integer NOT NULL auto_increment;
ALTER TABLE proficiency CHANGE proficiencyID proficiencyID integer NOT NULL auto_increment;
ALTER TABLE proficiency CHANGE personID personID integer NOT NULL;
ALTER TABLE proficiency CHANGE skillID skillID integer NOT NULL;
ALTER TABLE task CHANGE taskID taskID integer NOT NULL auto_increment;
ALTER TABLE task CHANGE creatorID creatorID integer NOT NULL;
ALTER TABLE task CHANGE closerID closerID integer default NULL;
ALTER TABLE task CHANGE projectID projectID integer DEFAULT NULL;
ALTER TABLE task CHANGE personID personID integer default NULL;
ALTER TABLE task CHANGE managerID managerID integer default NULL;
ALTER TABLE task CHANGE parentTaskID parentTaskID integer DEFAULT NULL;
ALTER TABLE task CHANGE taskTypeID taskTypeID integer NOT NULL default '1';
ALTER TABLE task CHANGE taskModifiedUser taskModifiedUser integer DEFAULT NULL;
ALTER TABLE task CHANGE taskCommentTemplateID taskCommentTemplateID integer default NULL;
ALTER TABLE task CHANGE duplicateTaskID duplicateTaskID integer default NULL;
ALTER TABLE task CHANGE priority priority integer NOT NULL DEFAULT 0;
ALTER TABLE auditItem CHANGE auditItemID auditItemID integer NOT NULL auto_increment;
ALTER TABLE auditItem CHANGE entityID entityID integer NOT NULL;
ALTER TABLE auditItem CHANGE personID personID integer NOT NULL;
ALTER TABLE interestedParty CHANGE interestedPartyID interestedPartyID integer NOT NULL auto_increment;
ALTER TABLE interestedParty CHANGE entityID entityID integer NOT NULL;
ALTER TABLE interestedParty CHANGE personID personID integer DEFAULT NULL;
ALTER TABLE interestedParty CHANGE clientContactID clientContactID integer DEFAULT NULL;
ALTER TABLE commentTemplate CHANGE commentTemplateID commentTemplateID integer NOT NULL auto_increment;
ALTER TABLE taskType CHANGE taskTypeID taskTypeID integer NOT NULL auto_increment;
ALTER TABLE taskType CHANGE taskTypeSequence taskTypeSequence integer default NULL;
ALTER TABLE tf CHANGE tfID tfID integer NOT NULL auto_increment;
ALTER TABLE tf CHANGE tfModifiedUser tfModifiedUser integer DEFAULT NULL;
ALTER TABLE tf CHANGE qpEmployeeNum qpEmployeeNum integer default NULL;
ALTER TABLE tfPerson CHANGE tfPersonID tfPersonID integer NOT NULL auto_increment;
ALTER TABLE tfPerson CHANGE tfID tfID integer NOT NULL;
ALTER TABLE tfPerson CHANGE personID personID integer NOT NULL;
ALTER TABLE timeSheet CHANGE timeSheetID timeSheetID integer NOT NULL auto_increment;
ALTER TABLE timeSheet CHANGE projectID projectID integer NOT NULL;
ALTER TABLE timeSheet CHANGE personID personID integer NOT NULL;
ALTER TABLE timeSheet CHANGE approvedByManagerPersonID approvedByManagerPersonID integer default NULL;
ALTER TABLE timeSheet CHANGE approvedByAdminPersonID approvedByAdminPersonID integer default NULL;
ALTER TABLE timeSheet CHANGE recipient_tfID recipient_tfID integer default NULL;
ALTER TABLE timeSheetItem CHANGE timeSheetItemID timeSheetItemID integer NOT NULL auto_increment;
ALTER TABLE timeSheetItem CHANGE timeSheetID timeSheetID integer NOT NULL;
ALTER TABLE timeSheetItem CHANGE personID personID integer NOT NULL;
ALTER TABLE timeSheetItem CHANGE taskID taskID integer default NULL;
ALTER TABLE timeSheetItem CHANGE timeSheetItemDurationUnitID timeSheetItemDurationUnitID integer default NULL;
ALTER TABLE timeSheetItem CHANGE multiplier multiplier integer NOT NULL DEFAULT 0;
ALTER TABLE timeUnit CHANGE timeUnitID timeUnitID integer NOT NULL auto_increment;
ALTER TABLE timeUnit CHANGE timeUnitSeconds timeUnitSeconds integer default NULL;
ALTER TABLE timeUnit CHANGE timeUnitSequence timeUnitSequence integer default NULL;
ALTER TABLE token CHANGE tokenID tokenID integer NOT NULL auto_increment;
ALTER TABLE token CHANGE tokenEntityID tokenEntityID integer;
ALTER TABLE token CHANGE tokenActionID tokenActionID integer NOT NULL;
ALTER TABLE token CHANGE tokenUsed tokenUsed integer DEFAULT 0;
ALTER TABLE token CHANGE tokenMaxUsed tokenMaxUsed integer DEFAULT 0;
ALTER TABLE token CHANGE tokenCreatedBy tokenCreatedBy integer NOT NULL;
ALTER TABLE tokenAction CHANGE tokenActionID tokenActionID integer NOT NULL auto_increment;
ALTER TABLE transaction CHANGE transactionID transactionID integer NOT NULL auto_increment;
ALTER TABLE transaction CHANGE expenseFormID expenseFormID integer DEFAULT NULL;
ALTER TABLE transaction CHANGE tfID tfID integer NOT NULL;
ALTER TABLE transaction CHANGE fromTfID fromTfID integer NOT NULL;
ALTER TABLE transaction CHANGE projectID projectID integer DEFAULT NULL;
ALTER TABLE transaction CHANGE transactionModifiedUser transactionModifiedUser integer DEFAULT NULL;
ALTER TABLE transaction CHANGE quantity quantity integer NOT NULL default '1';
ALTER TABLE transaction CHANGE transactionCreatedUser transactionCreatedUser integer DEFAULT NULL;
ALTER TABLE transaction CHANGE invoiceID invoiceID integer DEFAULT NULL;
ALTER TABLE transaction CHANGE invoiceItemID invoiceItemID integer default NULL;
ALTER TABLE transaction CHANGE timeSheetID timeSheetID integer default NULL;
ALTER TABLE transaction CHANGE productSaleID productSaleID integer default NULL;
ALTER TABLE transaction CHANGE productSaleItemID productSaleItemID integer default NULL;
ALTER TABLE transaction CHANGE transactionRepeatID transactionRepeatID integer default NULL;
ALTER TABLE transaction CHANGE transactionGroupID transactionGroupID integer default NULL;
ALTER TABLE transactionRepeat CHANGE transactionRepeatID transactionRepeatID integer NOT NULL auto_increment;
ALTER TABLE transactionRepeat CHANGE tfID tfID integer NOT NULL;
ALTER TABLE transactionRepeat CHANGE fromTfID fromTfID integer NOT NULL;
ALTER TABLE transactionRepeat CHANGE transactionRepeatModifiedUser transactionRepeatModifiedUser integer DEFAULT NULL;
ALTER TABLE transactionRepeat CHANGE transactionRepeatCreatedUser transactionRepeatCreatedUser integer DEFAULT NULL;
ALTER TABLE product CHANGE productID productID integer NOT NULL auto_increment;
ALTER TABLE productCost CHANGE productCostID productCostID integer NOT NULL auto_increment;
ALTER TABLE productCost CHANGE productID productID integer NOT NULL;
ALTER TABLE productCost CHANGE fromTfID fromTfID integer NOT NULL;
ALTER TABLE productCost CHANGE tfID tfID integer NOT NULL;
ALTER TABLE productSale CHANGE productSaleID productSaleID integer NOT NULL auto_increment;
ALTER TABLE productSale CHANGE clientID clientID integer DEFAULT NULL;
ALTER TABLE productSale CHANGE projectID projectID integer DEFAULT NULL;
ALTER TABLE productSale CHANGE productSaleCreatedUser productSaleCreatedUser integer default NULL;
ALTER TABLE productSale CHANGE productSaleModifiedUser productSaleModifiedUser integer default NULL;
ALTER TABLE productSaleItem CHANGE productSaleItemID productSaleItemID integer NOT NULL auto_increment;
ALTER TABLE productSaleItem CHANGE productID productID integer NOT NULL;
ALTER TABLE productSaleItem CHANGE productSaleID productSaleID integer NOT NULL;
ALTER TABLE productSaleItem CHANGE quantity quantity integer NOT NULL DEFAULT 1;


