-- Part 1: Make structure easier to manage, more in line with postgres syntax

ALTER TABLE absence CHANGE absenceID absenceID integer NOT NULL auto_increment;
ALTER TABLE absence CHANGE personID personID integer NOT NULL;
ALTER TABLE announcement CHANGE announcementID announcementID integer NOT NULL auto_increment;
ALTER TABLE announcement CHANGE personID personID integer NOT NULL;
ALTER TABLE client CHANGE clientID clientID integer NOT NULL auto_increment;
ALTER TABLE client CHANGE clientModifiedUser clientModifiedUser integer DEFAULT NULL;
ALTER TABLE client CHANGE clientCategory clientCategory integer DEFAULT 1;
ALTER TABLE clientContact CHANGE clientContactID clientContactID integer NOT NULL auto_increment;
ALTER TABLE clientContact CHANGE clientID clientID integer NOT NULL;
ALTER TABLE comment CHANGE commentID commentID integer NOT NULL auto_increment;
ALTER TABLE comment CHANGE commentLinkID commentLinkID integer NOT NULL;
ALTER TABLE comment CHANGE commentCreatedUser commentCreatedUser integer default NULL;
ALTER TABLE comment CHANGE commentModifiedUser commentModifiedUser integer DEFAULT NULL;
ALTER TABLE comment CHANGE commentCreatedUserClientContactID commentCreatedUserClientContactID integer DEFAULT NULL;
ALTER TABLE config CHANGE configID configID integer NOT NULL auto_increment;
ALTER TABLE expenseForm CHANGE expenseFormID expenseFormID integer NOT NULL auto_increment;
ALTER TABLE expenseForm CHANGE clientID clientID integer DEFAULT NULL;
ALTER TABLE expenseForm CHANGE expenseFormModifiedUser expenseFormModifiedUser integer DEFAULT NULL;
ALTER TABLE expenseForm CHANGE expenseFormCreatedUser expenseFormCreatedUser integer DEFAULT NULL;
ALTER TABLE expenseForm CHANGE transactionRepeatID transactionRepeatID integer DEFAULT NULL;
ALTER TABLE history CHANGE historyID historyID integer NOT NULL auto_increment;
ALTER TABLE history CHANGE personID personID integer NOT NULL;
ALTER TABLE invoice CHANGE invoiceID invoiceID integer NOT NULL auto_increment;
ALTER TABLE invoice CHANGE clientID clientID integer NOT NULL;
ALTER TABLE invoice CHANGE projectID projectID integer DEFAULT NULL;
ALTER TABLE invoice CHANGE invoiceNum invoiceNum integer NOT NULL;
ALTER TABLE invoiceItem CHANGE invoiceItemID invoiceItemID integer NOT NULL auto_increment;
ALTER TABLE invoiceItem CHANGE invoiceID invoiceID integer NOT NULL;
ALTER TABLE invoiceItem CHANGE timeSheetID timeSheetID integer DEFAULT NULL;
ALTER TABLE invoiceItem CHANGE timeSheetItemID timeSheetItemID integer DEFAULT NULL;
ALTER TABLE invoiceItem CHANGE expenseFormID expenseFormID integer DEFAULT NULL;
ALTER TABLE invoiceItem CHANGE transactionID transactionID integer DEFAULT NULL;
ALTER TABLE item CHANGE itemID itemID integer NOT NULL auto_increment;
ALTER TABLE item CHANGE itemModifiedUser itemModifiedUser integer DEFAULT NULL;
ALTER TABLE item CHANGE personID personID integer DEFAULT NULL;
ALTER TABLE loan CHANGE loanID loanID integer NOT NULL auto_increment;
ALTER TABLE loan CHANGE itemID itemID integer NOT NULL;
ALTER TABLE loan CHANGE personID personID integer NOT NULL;
ALTER TABLE loan CHANGE loanModifiedUser loanModifiedUser integer DEFAULT NULL;
ALTER TABLE patchLog CHANGE patchLogID patchLogID integer NOT NULL auto_increment;
ALTER TABLE permission CHANGE permissionID permissionID integer NOT NULL auto_increment;
ALTER TABLE permission CHANGE entityID entityID integer default NULL;
ALTER TABLE permission CHANGE personID personID integer default NULL;
ALTER TABLE permission CHANGE sortKey sortKey integer default '100';
ALTER TABLE permission CHANGE actions actions integer default NULL;
ALTER TABLE person CHANGE personID personID integer NOT NULL auto_increment;
ALTER TABLE person CHANGE personModifiedUser personModifiedUser integer DEFAULT NULL;
ALTER TABLE person CHANGE preferred_tfID preferred_tfID integer default NULL;
ALTER TABLE project CHANGE projectID projectID integer NOT NULL auto_increment;
ALTER TABLE project CHANGE clientID clientID integer DEFAULT NULL;
ALTER TABLE project CHANGE clientContactID clientContactID integer default NULL;
ALTER TABLE project CHANGE projectModifiedUser projectModifiedUser integer DEFAULT NULL;
ALTER TABLE project CHANGE projectPriority projectPriority integer default NULL;
ALTER TABLE project CHANGE cost_centre_tfID cost_centre_tfID integer default NULL;
ALTER TABLE projectCommissionPerson CHANGE projectCommissionPersonID projectCommissionPersonID integer NOT NULL auto_increment;
ALTER TABLE projectCommissionPerson CHANGE projectID projectID integer NOT NULL;
ALTER TABLE projectCommissionPerson CHANGE personID personID integer DEFAULT NULL;
ALTER TABLE projectCommissionPerson CHANGE tfID tfID integer NOT NULL;
ALTER TABLE projectPerson CHANGE projectPersonID projectPersonID integer NOT NULL auto_increment;
ALTER TABLE projectPerson CHANGE projectID projectID integer NOT NULL;
ALTER TABLE projectPerson CHANGE personID personID integer NOT NULL;
ALTER TABLE projectPerson CHANGE roleID roleID integer NOT NULL;
ALTER TABLE projectPerson CHANGE rateUnitID rateUnitID integer DEFAULT NULL;
ALTER TABLE projectPerson CHANGE projectPersonModifiedUser projectPersonModifiedUser integer DEFAULT NULL;
ALTER TABLE role CHANGE roleID roleID integer NOT NULL auto_increment;
ALTER TABLE role CHANGE roleSequence roleSequence integer default NULL;
ALTER TABLE reminder CHANGE reminderID reminderID integer NOT NULL auto_increment;
ALTER TABLE reminder CHANGE reminderLinkID reminderLinkID integer NOT NULL;
ALTER TABLE reminder CHANGE personID personID integer NULL default NULL;
ALTER TABLE reminder CHANGE metaPerson metaPerson integer NULL default NULL;
ALTER TABLE reminder CHANGE reminderRecuringValue reminderRecuringValue integer NOT NULL default '0';
ALTER TABLE reminder CHANGE reminderAdvNoticeValue reminderAdvNoticeValue integer NOT NULL default '0';
ALTER TABLE reminder CHANGE reminderModifiedUser reminderModifiedUser integer DEFAULT NULL;
ALTER TABLE sess CHANGE personID personID integer NOT NULL;

