
-- Add currency to transaction table and constraint
ALTER TABLE transaction ADD currencyTypeID VARCHAR(255) DEFAULT NULL AFTER amount; 
ALTER TABLE transaction ADD CONSTRAINT transaction_currencyTypeID FOREIGN KEY (currencyTypeID) REFERENCES currencyType (currencyTypeID);

-- Add currency to transactionRepeat table and constraint
ALTER TABLE transactionRepeat ADD currencyTypeID VARCHAR(255) DEFAULT NULL AFTER amount; 
ALTER TABLE transactionRepeat ADD CONSTRAINT transactionRepeat_currencyTypeID FOREIGN KEY (currencyTypeID) REFERENCES currencyType (currencyTypeID);

-- Add currency to productCost table and constraint
ALTER TABLE productCost ADD currencyTypeID VARCHAR(255) DEFAULT NULL AFTER amount; 
ALTER TABLE productCost ADD CONSTRAINT productCost_currencyTypeID FOREIGN KEY (currencyTypeID) REFERENCES currencyType (currencyTypeID);


-- Add a new label field to currencyType
ALTER TABLE currencyType ADD currencyTypeLabel VARCHAR(255) DEFAULT NULL AFTER currencyTypeID;
ALTER TABLE currencyType ADD currencyTypeName VARCHAR(255) DEFAULT NULL AFTER currencyTypeLabel;

-- Update new label field
UPDATE currencyType SET currencyTypeLabel = '$',currencyTypeName = 'United States dollar' WHERE currencyTypeID = 'USD';
UPDATE currencyType SET currencyTypeLabel = '$',currencyTypeName = 'Australian dollar' WHERE currencyTypeID = 'AUD';
UPDATE currencyType SET currencyTypeLabel = '$',currencyTypeName = 'Canadian dollar' WHERE currencyTypeID = 'CAD';
UPDATE currencyType SET currencyTypeLabel = '$',currencyTypeName = 'New Zealand dollar' WHERE currencyTypeID = 'NZD';

INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GBP','£','British pound','15',true);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('EUR','€','Euro','30',true);

INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AED','د.إ','United Arab Emirates dirham','11200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AFN','؋','Afghan afghani','100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ALL','L','Albanian lek','200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AMD','դր.','Armenian dram','7350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ANG','ƒ','Netherlands Antillean guilder','9600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AOA','Kz','Angolan kwanza','400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ARS','$','Argentine peso','550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AWG','ƒ','Aruban florin','650',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('AZN','m','Azerbaijani manat','850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BAM','KM','Bosnia and Herzegovina convertible mark','1500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BBD','$','Barbadian dollar','1050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BDT','৳','Bangladeshi taka','1000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BGN','лв','Bulgarian lev','1800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BHD','.د.ب','Bahraini dinar','950',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BIF','Fr','Burundian franc','1950',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BMD','$','Bermudian dollar','1300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BND','$','Brunei dollar','9500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BOB','Bs.','Bolivian boliviano','1400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BRL','R$','Brazilian real','1600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BSD','$','Bahamian dollar','900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BTN','Nu.','Bhutanese ngultrum','1350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BWP','P','Botswana pula','1550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BYR','Br','Belarusian ruble','1100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('BZD','$','Belize dollar','1200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CDF','Fr','Congolese franc','2600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CHF','Fr','Swiss franc','6200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CLP','$','Chilean peso','2350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CNY','¥','Chinese yuan','2400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('COP','$','Colombian peso','2500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CRC','₡','Costa Rican colón','2750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CUC','$','Cuban convertible peso','2900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CVE','?','Cape Verdean escudo','2150',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('CZK','Kč','Czech koruna','3050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('DJF','Fr','Djiboutian franc','3150',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('DKK','kr','Danish krone','3750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('DOP','$','Dominican peso','3250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('DZD','د.ج','Algerian dinar','300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('EEK','kr','Estonian kroon','3600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('EGP','ج.م','Egyptian pound','3400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ERN','Nfk','Eritrean nakfa','3550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ETB','Br','Ethiopian birr','3650',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('FJD','$','Fijian dollar','3800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('FKP','£','Falkland Islands pound','3700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GEL','ლ','Georgian lari','4100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GHS','₵','Ghanaian cedi','4200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GIP','£','Gibraltar pound','4250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GMD','D','Gambian dalasi','4050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GNF','Fr','Guinean franc','4500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GTQ','Q','Guatemalan quetzal','4400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('GYD','$','Guyanese dollar','4600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('HKD','$','Hong Kong dollar','4750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('HNL','L','Honduran lempira','4700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('HRK','kn','Croatian kuna','2850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('HTG','G','Haitian gourde','4650',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('HUF','Ft','Hungarian forint','4800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('IDR','Rp','Indonesian rupiah','4950',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ILS','₪','Israeli new sheqel','8200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('INR','?','Indian rupee','4900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('IQD','ع.د','Iraqi dinar','5050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('IRR','﷼','Iranian rial','5000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ISK','kr','Icelandic króna','4850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('JMD','$','Jamaican dollar','5300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('JOD','د.ا','Jordanian dinar','5450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('JPY','¥','Japanese yen','5350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KES','Sh','Kenyan shilling','5550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KGS','лв','Kyrgyzstani som','5850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KHR','៛','Cambodian riel','2000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KMF','Fr','Comorian franc','2550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KPW','₩','North Korean won','5650',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KRW','₩','South Korean won','5700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KWD','د.ك','Kuwaiti dinar','5800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KYD','$','Cayman Islands dollar','2200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('KZT','₸','Kazakhstani tenge','5500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LAK','₭','Lao kip','5900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LBP','ل.ل','Lebanese pound','6000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LKR','Rs','Sri Lankan rupee','10100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LRD','$','Liberian dollar','6100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LSL','L','Lesotho loti','6050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LTL','Lt','Lithuanian litas','6250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LVL','Ls','Latvian lats','5950',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('LYD','ل.د','Libyan dinar','6150',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MAD','د.م.','Moroccan dirham','7250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MDL','L','Moldovan leu','7000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MGA','Ar','Malagasy ariary','6450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MKD','ден','Macedonian denar','6400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MMK','K','Myanma kyat','1900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MNT','₮','Mongolian tögrög','7100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MOP','P','Macanese pataca','6350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MRO','UM','Mauritanian ouguiya','6800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MUR','₨','Mauritian rupee','6850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MVR','ރ.','Maldivian rufiyaa','6600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MWK','MK','Malawian kwacha','6500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MXN','$','Mexican peso','6900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MYR','RM','Malaysian ringgit','6550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('MZN','MTn','Mozambican metical','7300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('NAD','$','Namibian dollar','7400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('NGN','₦','Nigerian naira','7800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('NIO','C$','Nicaraguan córdoba','7700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('NOK','kr','Norwegian krone','8000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('NPR','₨','Nepalese rupee','7500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('OMR','ر.ع.','Omani rial','8050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PAB','B/.','Panamanian balboa','8250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PEN','S/.','Peruvian nuevo sol','8400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PGK','K','Papua New Guinean kina','8300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PHP','₱','Philippine peso','8450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PKR','₨','Pakistani rupee','8100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PLN','zł','Polish złoty','8550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('PYG','₲','Paraguayan guaraní','8350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('QAR','ر.ق','Qatari riyal','8650',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('RON','L','Romanian leu','8700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('RSD','дин.','Serbian dinar','9350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('RUB','р.','Russian ruble','10000',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('RWF','Fr','Rwandan franc','8800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SAR','ر.س','Saudi riyal','9250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SBD','$','Solomon Islands dollar','9750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SCR','₨','Seychellois rupee','9400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SDG','£','Sudanese pound','10150',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SEK','kr','Swedish krona','10300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SHP','£','Saint Helena pound','8900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SLL','Le','Sierra Leonean leone','9450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SOS','Sh','Somali shilling','9800',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SRD','$','Surinamese dollar','10200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('STD','Db','São Tomé and Príncipe dobra','9200',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SVC','₡','Salvadoran colón','3450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SYP','ل.س','Syrian pound','10400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('SZL','L','Swazi lilangeni','10250',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('THB','฿','Thai baht','10600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TJS','ЅМ','Tajikistani somoni','10500',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TMM','m','Turkmenistani manat','10950',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TND','د.ت','Tunisian dinar','10850',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TOP','T$','Tongan paʻanga','10700',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TRY','₤','Turkish lira','7900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TTD','$','Trinidad and Tobago dollar','10750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TWD','$','New Taiwan dollar','10450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('TZS','Sh','Tanzanian shilling','10550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('UAH','₴','Ukrainian hryvnia','11150',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('UGX','Sh','Ugandan shilling','11100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('UYU','$','Uruguayan peso','11350',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('UZS','лв','Uzbekistani som','11400',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('VEF','Bs F','Venezuelan bolívar','11550',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('VND','₫','Vietnamese đồng','11600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('VUV','Vt','Vanuatu vatu','11450',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('WST','T','Samoan tala','9100',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('XAF','Fr','Central African CFA franc','2050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('XCD','$','East Caribbean dollar','9050',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('XOF','Fr','West African CFA franc','9300',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('XPF','Fr','CFP franc','7600',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('YER','﷼','Yemeni rial','11750',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ZAR','R','South African rand','9900',false);
INSERT INTO currencyType (currencyTypeID,currencyTypeLabel,currencyTypeName,currencyTypeSeq,currencyTypeActive) VALUES ('ZMK','ZK','Zambian kwacha','11800',false);
