version: "2"
checks:
  file-lines:
    enabled: false
exclude_patterns:
- "**/*.css"
- "**/*.ini"
- "**/*.tpl"
- "**/*.py"
- "**/*.js"
- "zend/"
- "shared/lib/"
- "email/lib/Mail_RFC822.inc.php"
- "email/lib/Mail_mimeDecode.inc.php"
- "wiki/lib/markdown.inc.php"
