<tr>
  <td>{transaction_transactionDate}</td>
  <td>{transaction_product}</td>
  <td>{transaction_tfID}</td>
  <td>{transaction_amount}</td>
  <td>{transaction_transactionType}</td>
  <td>{transaction_status}</td>									  
  <td>&nbsp;</td>
</tr>
