<tr>
  <td{$calendar_class_Sun}>
    <h1>{$calendar_Sun_links}{$calendar_Sun_date}</h1>
    {$calendar_Sun_started}
    {$calendar_Sun_completed}
    {$calendar_Sun_reminders}
  </td>
  <td{$calendar_class_Mon}>
    <h1>{$calendar_Mon_links}{$calendar_Mon_date}</h1>
    {$calendar_Mon_started}
    {$calendar_Mon_completed}
    {$calendar_Mon_reminders}
  </td>
  <td{$calendar_class_Tue}>
    <h1>{$calendar_Tue_links}{$calendar_Tue_date}</h1>
    {$calendar_Tue_started}
    {$calendar_Tue_completed}
    {$calendar_Tue_reminders}
  </td>
  <td{$calendar_class_Wed}>
    <h1>{$calendar_Wed_links}{$calendar_Wed_date}</h1>
    {$calendar_Wed_started}
    {$calendar_Wed_completed}
    {$calendar_Wed_reminders}
  </td>
  <td{$calendar_class_Thu}>
    <h1>{$calendar_Thu_links}{$calendar_Thu_date}</h1>
    {$calendar_Thu_started}
    {$calendar_Thu_completed}
    {$calendar_Thu_reminders}
  </td>
  <td{$calendar_class_Fri}>
    <h1>{$calendar_Fri_links}{$calendar_Fri_date}</h1>
    {$calendar_Fri_started}
    {$calendar_Fri_completed}
    {$calendar_Fri_reminders}
  </td>
  <td{$calendar_class_Sat}>
    <h1>{$calendar_Sat_links}{$calendar_Sat_date}</h1>
    {$calendar_Sat_started}
    {$calendar_Sat_completed}
    {$calendar_Sat_reminders}
  </td>
</tr>
